### ISSUE TITLE
Suggestion: Add Placeholder Support

### ISSUE THREAD

**Issue by SkyNetCloud** [nichogx/DiscordRoleSync#12]
I wanted to use the placeholder API to show bedrock players UUID so they then can send me that UUID so I can manually add them to the MySQL database as this plugin doesn't yet support bedrock UUID grabbing

**Comment by nichogx** [comment]
You can manually add people to the database by UUID if you want, what would placeholder API integration mean here?

However, bedrock is not supported and it won't be, this is a Java only plugin.
