### ISSUE TITLE
Add 1.17 support

### ISSUE THREAD

**Issue by QuanTrieuPCYT** [nichogx/DiscordRoleSync#13]
The plugin is not working properly on 1.17. My players can't join the server (i turned on verification and whitelist thingy) and i had to temporarily disable the plugin. Any help?

**Comment by nichogx** [comment]
Please have patience, Paper 1.17 hasn't even come out yet. Also there shouldn't be many breaking changes on 1.17 so it should work. Did it work for you before, on 1.16? Please join the Discord server for additional support if needed.

**Comment by QuanTrieuPCYT** [comment]
It did work for me on 1.16.5 but not on Spigot 1.17. Ok i'll wait for PaperMC 1.17 tho and feedback you

**Comment by QuanTrieuPCYT** [comment]
ok forgot to close the issue lol. Latest version of Vault and Purpur 1.17.1 made the plugin working.
