### ISSUE TITLE
An error occurred while trying to check link the user. Please check the stack trace below and contact the developer.

### ISSUE THREAD

**Issue by SleepyScallop** [nichogx/DiscordRoleSync#15]
06.03 12:57:29 [Server] ERROR [DiscordRoleSync] An error occurred while trying to check link the user. Please check the stack trace below and contact the developer.
06.03 12:57:29 [Server]  java.io.IOException: Server returned HTTP response code: 429 for URL: https://api.mojang.com/users/profiles/minecraft/FauconSau6
06.03 12:57:29 [Server]  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1985)
06.03 12:57:29 [Server]  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
06.03 12:57:29 [Server]  at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
06.03 12:57:29 [Server]  at discord_role_sync-1.0.1.jar//dev.nicho.rolesync.util.MojangAPI.nameToUUID(MojangAPI.java:101)
06.03 12:57:29 [Server]  at discord_role_sync-1.0.1.jar//dev.nicho.rolesync.SyncBot$CommandHandler.linkUser(SyncBot.java:483)
06.03 12:57:29 [Server]  at discord_role_sync-1.0.1.jar//dev.nicho.rolesync.SyncBot$CommandHandler.link(SyncBot.java:346)
06.03 12:57:29 [Server]  at discord_role_sync-1.0.1.jar//dev.nicho.rolesync.SyncBot.onMessageReceived(SyncBot.java:104)
06.03 12:57:29 [Server]  at discord_role_sync-1.0.1.jar//net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:427)
06.03 12:57:29 [Server]  at discord_role_sync-1.0.1.jar//net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
06.03 12:57:29 [Server]  at discord_role_sync-1.0.1.jar//net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:82)
06.03 12:57:29 [Server]  at discord_role_sync-1.0.1.jar//net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:69)
06.03 12:57:29 [Server]  at discord_role_sync-1.0.1.jar//net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:166)
06.03 12:57:29 [Server]  at discord_role_sync-1.0.1.jar//net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122)
06.03 12:57:29 [Server]  at discord_role_sync-1.0.1.jar//net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
06.03 12:57:29 [Server]  at discord_role_sync-1.0.1.jar//net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:905)
06.03 12:57:29 [Server]  at discord_role_sync-1.0.1.jar//net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:792)
06.03 12:57:32 [Server]  at discord_role_sync-1.0.1.jar//net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:770)
06.03 12:57:32 [Server]  at discord_role_sync-1.0.1.jar//net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:943)
06.03 12:57:32 [Server]  at discord_role_sync-1.0.1.jar//com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
06.03 12:57:32 [Server]  at discord_role_sync-1.0.1.jar//com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
06.03 12:57:32 [Server]  at discord_role_sync-1.0.1.jar//com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
06.03 12:57:32 [Server]  at discord_role_sync-1.0.1.jar//com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
06.03 12:57:32 [Server]  at discord_role_sync-1.0.1.jar//com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
06.03 12:57:32 [Server]  at discord_role_sync-1.0.1.jar//com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
06.03 12:57:32 [Server]  at discord_role_sync-1.0.1.jar//com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

**Comment by nichogx** [comment]
you're being rate limited by Mojang's API. 429 means too many requests

**Comment by SleepyScallop** [comment]
> you're being rate limited by Mojang's API. 429 means too many requests

This is my first link in weeks. Your plugin worked on 1.18.1

**Comment by nichogx** [comment]
something must have changed with your hosting providers. maybe combined IPs with another server who is making a lot of requests. If Mojang's API is returning a 429 there is nothing I can do unfortunately. This is not an issue with the plugin.

**Comment by SleepyScallop** [comment]
> something must have changed with your hosting providers. maybe combined IPs with another server who is making a lot of requests. If Mojang's API is returning a 429 there is nothing I can do unfortunately. This is not an issue with the plugin.

So if im using a shared host and we all get the same ip's but different ports, this could be the issue?

**Comment by nichogx** [comment]
Yes, that could be the issue. That was an issue I had with PebbleHost once on a server a long time ago.

**Comment by SleepyScallop** [comment]
> Yes, that could be the issue. That was an issue I had with PebbleHost once on a server a long time ago.

Yes i am using pebble host. Hope to soon have my own ip. sad i cant use your plugin until then. Thanks!
