### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by avafloww** [nichogx/DiscordRoleSync#2]
By default, works published without an explicit license remain unlicensed, leaving their modification and use in a legal gray area at best. Please add a `LICENSE` file to the project to remedy this!

I'm a bit biased towards the [MIT License](https://tldrlegal.com/license/mit-license) myself for its extreme "do whatever you want as long as you credit the author" approach, but there are also [many other licenses you can choose from](https://tldrlegal.com/).

**Comment by nichogx** [comment]
Thanks for the reminder! I totally forgot to add it when I made this public.
