### ISSUE TITLE
Periodic Role Reload

### ISSUE THREAD

**Issue by ChoosenEye** [nichogx/DiscordRoleSync#4]
we currently have the Issue that not all Groups will be transferred every time when the User joins first.

Is there a way to add a Periodic Updates of all User for their Groups?

Like every 10mins the Bot will check if the User Groups are correct representing the Discord Groups.

**Comment by nichogx** [comment]
currently there is no way to add periodic updates, but the check is done every time the server restarts.

normally the group is given as soon as the user is linked/as soon as the user receives the discord role.

**Comment by ChoosenEye** [comment]
hmm okay.

so when it's reloading on restart can you add a reload roles command?

**Comment by nichogx** [comment]
Is this still needed? Have you found a workaround?

**Comment by nichogx** [comment]
closing since no response
