### ISSUE TITLE
Add Default Role

### ISSUE THREAD

**Issue by ChoosenEye** [nichogx/DiscordRoleSync#5]
We have a Discord where normal basic Users dont have a Role.

Would be perfect to say "whitelist all People on Server false/true" instead of a ID List, and a Default Permission Group which will be granted after Join even if no Discord Group is available.

**Comment by nichogx** [comment]
this functionality can be achieved by making use of the whitelist functionality of the plugin. Set the whitelist role as the same one as your linked role. Users link themselves, receive the linked role and as such are able to login

**Comment by ChoosenEye** [comment]
thats what we currently use, works but not perfect imo.

in Best Case we would like to not use a linked role, maybe this could be inserted in a later update.
